---
openapi: '3.0.0'
info:
  title: Swagger LoveYouForms
  description: This is API documentation for LoveYouForms. You can find out more about LoveYouForms at [https://loveyouforms.com](https://loveyouforms.com).<br><br>
    See the <strong><u>source package code</u></strong> [https://github.com/LoveYouFyi/loveyouforms-package](https://github.com/LoveYouFyi/loveyouforms-package)<br>
    See the <strong><u>app wrapper code</u></strong> [https://github.com/LoveYouFyi/loveyouforms](https://github.com/LoveYouFyi/loveyouforms)<br>
tags:
  - name: Send Form
paths:
  "/formHandler":
    post:
      tags:
      - Send Form
      summary: Send form
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              "$ref": "#/definitions/contactDefault"
            examples:
              contactDefault:
                value:
                  service: Node.js Development
                  budget: $20,000 or more
                  timeframe: Within 3 months
                  name: Erik Hendrick
                  phone: 904-555-1212
                  email: erik@loveyou.fyi
                  message: Hi, how are you!?
                  urlAction: http://localhost:5001/loveyou-forms/us-central1/formHandler
                  appKey: LOVEYOUFORMS8GCXSg6fbLgteaWDLnTwL2EC3Kj7y4kDWqGU4Vzcq8UQKAzfZvJ4xkjTv8GjXKvdEs6BHGjU
                  urlRedirect: false
                  templateName: contactDefault
                  webformId: contact1
              contactAlt:
                value:
                  name: Erik Hendrick
                  email: erik@loveyou.fyi
                  message: Hi, how are you!?
                  urlAction: http://localhost:5001/loveyou-forms/us-central1/formHandler
                  appKey: LOVEYOUFORMS8GCXSg6fbLgteaWDLnTwL2EC3Kj7y4kDWqGU4Vzcq8UQKAzfZvJ4xkjTv8GjXKvdEs6BHGjU
                  urlRedirect: false
                  templateName: contactAlt
                  webformId: contact2
      responses:
        '200':
          description: success
        '403':
          description: Forbidden
definitions:
  contactDefault:
    type: object
    properties:
      service:
        type: string
        example: Node.js Development
      budget:
        type: string
        example: $20,000 or more
      timeframe:
        type: string
        example: Within 3 months
      name:
        type: string
        example: Erik Hendrick
      phone:
        type: string
        example: 904-555-1212
      email:
        type: string
        example: erik@loveyou.fyi
      message:
        type: string
        example: Hi, how are you!?
      urlAction:
        type: string
        example: http://localhost:5001/loveyou-forms/us-central1/formHandler
      appKey:
        type: string
        example: LOVEYOUFORMS8GCXSg6fbLgteaWDLnTwL2EC3Kj7y4kDWqGU4Vzcq8UQKAzfZvJ4xkjTv8GjXKvdEs6BHGjU
      urlRedirect:
        type: string
        example: false
      templateName:
        type: string
        example: contactDefault
      webformId:
        type: string
        example: contact1


